//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscordInteraction) DeepCopyInto(out *DiscordInteraction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscordInteraction.
func (in *DiscordInteraction) DeepCopy() *DiscordInteraction {
	if in == nil {
		return nil
	}
	out := new(DiscordInteraction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscordInteraction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscordInteractionList) DeepCopyInto(out *DiscordInteractionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiscordInteraction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscordInteractionList.
func (in *DiscordInteractionList) DeepCopy() *DiscordInteractionList {
	if in == nil {
		return nil
	}
	out := new(DiscordInteractionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscordInteractionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscordInteractionSpec) DeepCopyInto(out *DiscordInteractionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscordInteractionSpec.
func (in *DiscordInteractionSpec) DeepCopy() *DiscordInteractionSpec {
	if in == nil {
		return nil
	}
	out := new(DiscordInteractionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscordInteractionStatus) DeepCopyInto(out *DiscordInteractionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscordInteractionStatus.
func (in *DiscordInteractionStatus) DeepCopy() *DiscordInteractionStatus {
	if in == nil {
		return nil
	}
	out := new(DiscordInteractionStatus)
	in.DeepCopyInto(out)
	return out
}
