# permissions for end users to edit discordinteractions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vahkane
    app.kubernetes.io/managed-by: kustomize
  name: discordinteraction-editor-role
rules:
- apiGroups:
  - vahkane.anqou.net
  resources:
  - discordinteractions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vahkane.anqou.net
  resources:
  - discordinteractions/status
  verbs:
  - get
