---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vahkane.anqou.net
  resources:
  - discordinteractions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vahkane.anqou.net
  resources:
  - discordinteractions/finalizers
  verbs:
  - update
- apiGroups:
  - vahkane.anqou.net
  resources:
  - discordinteractions/status
  verbs:
  - get
  - patch
  - update
